export const ICONS = {
  home: 'home',
  folder: 'folder',
  fileText: 'file-text',
  user: 'user',
  phone: 'phone',
  arrowRight: 'arrow-right',
  chevronRight: 'chevron-right',
  arrowLeft: 'arrow-left',
  check: 'check',
  checkCircle: 'check-circle',
  star: 'star',
  heart: 'heart',
  share: 'share-2',
  settings: 'settings',
  help: 'help-circle',
  message: 'message-circle',
  logout: 'log-out',
  shield: 'shield',
  monitor: 'monitor',
  grid: 'grid',
  edit: 'edit-3',
  key: 'key',
  layers: 'layers',
  box: 'box',
  eye: 'eye',
  tool: 'tool',
  square: 'square',
  dollarSign: 'dollar-sign',
};

export default ICONS;
